### ISSUE TITLE
vendor

### ISSUE THREAD

**Issue by kingofching** [AppSaloon/condolence-manager#11]
This error occurs upon activation.

Warning: require_once(/var/www/vhosts/xxxxxx.net/httpdocs/xxxxxx/wp-content/plugins/condolence-manager-master/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/xxxxxxxxx.net/httpdocs/xxxxxxxx/wp-content/plugins/condolence-manager-master/condolatie-manager.php on line 57

**Comment by koenHuybrechts** [comment]
Did you download the release? (https://github.com/AppSaloon/condolence-manager/releases/tag/2.10.1) 
Or did you clone the repository? In this case, you have to install all composer packages.

**Comment by kingofching** [comment]
My bad. I cloned the repository. I apologize.

Thank you,

Steve
